FROM golang:1.17-alpine
RUN apk --no-cache add git build-base bind-tools ca-certificates
ENV GO111MODULE on

RUN GO111MODULE=on go install github.com/dwisiswant0/crlfuzz/cmd/crlfuzz@latest
RUN ln -s /root/go/bin/crlfuzz /usr/local/bin/crlfuzz

ENTRYPOINT ["crlfuzz"]